[package]
name = "booru-grabber"
version = "0.1.0"
authors = ["crab"]
edition = "2018"

[[bin]]
name = "booru-grabber"
[dependencies]
error-chain = "0.12.0"
serde_json = "1.0.33"
serde_derive = "1.0.80"
serde-xml-rs = "0.2.1"
serde = "1.0.80"
clap = "2.32.0"
reqwest = "0.9.4"
url = "1.7.2"
